services:
  registry:
    build:
      context: ./RegistryService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - test-net

networks:
  test-net:
    driver: bridge
